--- 
title: "Analysis of stocks discussed in Reddit r/wallstreetbets"
author: "Xingyu Lu, Yue Xiong ,Yue Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction


Background:
In January, 2021, there is a subreddit called r/wallstreetbets where participants discuss stocks and option trading. Previously, there are not much redditers discussing in this subreddit group. Only until January 2021, there was one person started to share his investment in `GameStop`, with the ticker to be `GME`, and explained his rationale. This posts started to get the public attention and also, the redditers discovered that `GME` has been over short by some major financial institute, i.e. short interest is greater than 100%. This attracted more and more people into the r/wallstreetbets. The newly joined people are mainly young retailer traders who have little background in investment knowledge and risk management. They were not satisfied with the over short on some stocks by major Wall Street companies, so they started to buy those stocks, mostly `GME`. They were especially angered by the Citron Research's comment, which predicted the `GME`'s stock price would decrease continuously. This actually initiated a short squeeze on `GME`, pushing their stock prices up significantly. After a few days, Elon Musk also tweeted out a link to the r/wallstreetbets subreddit, which further enlightened the redditers and broadcasted to even more people all over the world. Later on, the official r/wallstreetbets Discord server was banned due to the "hateful and discriminatory content" and Robinhood started to restricted the trade of heavily shorted stocks such as `GME`, `AMC Entertainment Holdings Inc` (`AMC`), `BlackBerry Limited` (`BB`), `Nokia` (`NOK`), and etc. Other trading platform also followed Robinhood to restrict the trade of those stocks, which were TD Ameritrade, E-Trade, and Webull respectively. 

There were 2 waves of major short squeeze led by the participants in this subreddit, which were around January/Feburary and May/June period. Also, the focus of the 2 waves were different, while for the 1st wave, `GME` is the focus stock, `AMC` overtaken `GME` became the focus stock in the 2nd wave.

In this project, we would like to collect stock related data, Reddit related data (mainly posts) as well as the Google search related data to generate visualization and get some useful insights. We'll be trying to answer following questions through this study:

1. How big is the impact of reddit wallstreetbet? I.e. no. of news, downloads of Robinhood and other trading apps,

2. For each targeted stock, what’s the relationship between reddit posts and stock price/volume etc.

3. Why does Wallstreetbet choose these target stocks? What’re their similarities? How do their choices change as time evolves? Gamestop, AMC, Blueberry, Nokia, SPCE, PLTR, TSLA.

In the following chapters, we will use data source to plot graphs, trying to answer the above questions. Also, we would like to explore other aspects from the graphs and come up with more conclusions.

For more details of this project, click the link here or copy the url https://github.com/stellazhangyue/redditWSB.git and open it in browser to go to our Github repository and navigate code in .Rmd files.